# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://firsh.me
date_format: "ordinal"
title: ??????
subtitle: "What is bitter, what is difficult, what is high, and how far away."
description: "???????"
keywords: ???, Zhuang Ma, mzlogin, mazhuang,????,docker,Docker,Dockerfile,zmatsh
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/zmatsh/zmatsh.github.io/
side_bar_repo_limit: 6

# ---------------- #
#      Author      #
# ---------------- #
author: ?????
organization: Winhong, Inc.
organization_url: https://winhong.com
location: Beijing, China
email: zhang-rd-fe@s139.org
# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: ??
  -
    href: /categories/
    label: ??

  -
    href: /open-source/
    label: ??

  -
    href: /wiki/
    label: ??
  -
    href: /links/
    label: ??
  -
    href: /about/
    label: ??
# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml
# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
    - jekyll-github-metadata
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
# ---------------- #
#      Socials     #
# ---------------- #
github_username: zmatsh
#douban_username: zmatsh
facebook_username: zmatsh
#weibo_username: zmatsh
#zhihu_username: zmatsh
#twitter_username: zmatsh
# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
#comments_provider: disqus
# !!!??!!! ?????????????????
# !!!Important!!! Please modify usernames below to yours
#duoshuo_username: mazhuang
#disqus_username: mzlogin
# ??? disqus ?????????????
#lazy_load_duoshuo: true
# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C, Python, Golang,??]
skill_mobile_app_keywords: [Android, Wex5, phoneGap]
#skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
# ---------------- #
# Github metadata  #
# ---------------- #
gems: ['jekyll-github-metadata','jekyll-paginate','jekyll-feed']
repository: zmatsh/zmatsh.github.io
