# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://firsh.me
date_format: "ordinal"
title: 张建新
subtitle: "任何能轻易得到的东西，都值得你珍惜."
description: "Flink，张建新技术博客，Kubernetes技术，虚拟化技术，微服务，容器技术,docker,Github, Google Kubernetes, kubernetes, Flink,Graphx,Spark,docker。"
keywords: 张建新,docker,Github, 张建新博客 Google Kubernetes, kubernetes, Flink,Graphx Spark,hadoop,hbase,mongodb,hdfs,Geek,hack,Spring boot,spring boot,spring,Docker,Dockerfile,Java ,Python 冷漠
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/uk0/uk0.github.io/
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: unknow :)
organization: Huching Inc.
organization_url: https://www.huaching.com
location: China
email: zhang-rd-fe@s139.org

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Index

  -
    href: /categories/
    label: CATEGORIES

  -
    href: /open-source/
    label: OPEN-SOURCE

  -
    href: /wiki/
    label: WIKI

  -
    href: /links/
    label: LINKS

  -
    href: /about/
    label: ABOUT

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
    - jekyll-github-metadata
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: uk0
#douban_username: zmatsh
facebook_username: zmatsh
#weibo_username: zmatsh
#zhihu_username: zmatsh
twitter_username: firshMe

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
#duoshuo_username: JianXinZhang
disqus_username: zmatsh
# 在使用 disqus 的时候可点击显示多说评论框
#lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C, Python, Golang,JavaScript,Docker,Hadoop,Hbase,Flink,Storm,CrateDb,MongoDB,Kubernetes,Linux]
skill_mobile_app_keywords: [Android, Wex5, phoneGap,DSM]
#skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]

# ---------------- #
# Github metadata  #
# ---------------- #
#gems: ['jekyll-github-metadata','jekyll-paginate','jekyll-feed']
repository: uk0/uk0.github.io
