# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://firsh.me
date_format: "ordinal"
title: HappyFramework :)
subtitle: "What is bitter, what is difficult, what is high, and how far away."
description: "Flink，张建新技术博客，Kubernetes技术，虚拟化技术，微服务，容器技术,docker,Github, Google Kubernetes, kubernetes, Flink,Graphx,Spark,docker。"
keywords: 会飞的胖子,docker,Github, Google Kubernetes, kubernetes, Flink,Graphx Spark,docker,Docker,Dockerfile,zmatsh
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/zmatsh/zmatsh.github.io/
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zmatsh
organization: TimeOnData, Inc.
organization_url: https://timeondata.com
location: Beijing, China
email: zhang-rd-fe@s139.org

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类
  
  -
    href: /open-source/
    label: 开源
    
  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
    - jekyll-github-metadata
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: zmatsh
#douban_username: zmatsh
facebook_username: zmatsh
#weibo_username: zmatsh
#zhihu_username: zmatsh
twitter_username: firshMe

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
#duoshuo_username: JianXinZhang
disqus_username: zmatsh
# 在使用 disqus 的时候可点击显示多说评论框
#lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C, Python, Golang,前端,Docker,swagger,kubernetes,linux]
skill_mobile_app_keywords: [Android, Wex5, phoneGap]
#skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]

# ---------------- #
# Github metadata  #
# ---------------- #
#gems: ['jekyll-github-metadata','jekyll-paginate','jekyll-feed']
repository: zmatsh/zmatsh.github.io
