# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://firsh.me
date_format: "ordinal"
title: firshme
subtitle: "因军刀认识小榕结交流光,下一个9年何去何从。"
description: "张建新个人博客,我没有生来天赋过人,只有对技术的虔诚。"
keywords: 张建新,docker,Github, 张建新博客 Google Kubernetes, kubernetes, Flink,Graphx Spark,hadoop,hbase,mongodb,hdfs,Geek,hack,Spring boot,spring boot,spring,Docker,Dockerfile,Java ,Python 冷漠
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 6

# ---------------- #
#      Author      #
# ---------------- #
author: ZhangJianXin
organization: WaterElephant
organization_url: http://www.waterelephant.cn
github_username: uk0
location: BeiJing, China
email: zhang-rd-fe@s139.org

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: uk0/uk0.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk

gitalk:
    owner: uk0
    repo: blog-comments
    clientID: 0dc80b46a482ec78f3e0
    clientSecret: 8cae5d306b3703ad240b74142995473086fcbbab
# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-130872028-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C, Python, Golang,JavaScript,Docker,Hadoop,Hbase,Flink,Storm,CrateDb,MongoDB,Kubernetes,Linux]
skill_mobile_app_keywords: [Android, Wex5, phoneGap,DSM]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]

# ---------------- #
# Github metadata  #
# ---------------- #
#gems: ['jekyll-github-metadata','jekyll-paginate','jekyll-feed']
repository: uk0/uk0.github.io